import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import path from 'path';
import { fileURLToPath } from 'url';
import { testDatabase } from './db.js';
import authRoutes from './routes/auth.js';
import productRoutes from './routes/products.js';
import brandRoutes from './routes/brands.js';
import categoryRoutes from './routes/categories.js';
import orderRoutes from './routes/orders.js';
import adminRoutes from './routes/admin.js';
import settingsRoutes from './routes/settings.js';

const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);
const app=express();
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'}));
app.use(express.json({limit:'1mb'}));app.use(morgan('dev'));
app.use('/api',rateLimit({windowMs:15*60*1000,max:500,standardHeaders:true,legacyHeaders:false}));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.get('/api/health',async(_,res)=>{try{await testDatabase();res.json({ok:true,service:'KPK Electronics API',database:'mysql'})}catch(e){res.status(503).json({ok:false,message:'Database unavailable'})}});
app.use('/api/auth',authRoutes);app.use('/api/products',productRoutes);app.use('/api/brands',brandRoutes);app.use('/api/categories',categoryRoutes);app.use('/api/orders',orderRoutes);app.use('/api/admin',adminRoutes);app.use('/api/settings',settingsRoutes);
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Unexpected server error'})});
const port=Number(process.env.PORT||5000);
async function start(){if(!process.env.DB_NAME)throw new Error('DB_NAME is missing. Run npm run setup first.');if(!process.env.JWT_SECRET)throw new Error('JWT_SECRET is missing.');await testDatabase();console.log('MySQL connected');app.listen(port,()=>console.log(`KPK Electronics API running on http://localhost:${port}`));}
start().catch(err=>{console.error(`Startup failed: ${err.message}`);process.exit(1)});
