-- KPK Electronics MySQL/MariaDB import generated from the supplied MongoDB export.
-- Includes 22 brands, 12 categories, 45 products, 2 users, and store settings.
-- Product image paths are preserved exactly as exported.

CREATE DATABASE IF NOT EXISTS kpk_electronics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kpk_electronics;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('customer','admin') NOT NULL DEFAULT 'customer',
  phone VARCHAR(50) NULL,
  addresses JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS brands (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  slug VARCHAR(180) NOT NULL UNIQUE,
  country VARCHAR(120) NULL,
  description TEXT NULL,
  logo VARCHAR(500) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  slug VARCHAR(180) NOT NULL UNIQUE,
  icon VARCHAR(500) NULL,
  description TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(280) NOT NULL UNIQUE,
  brand_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(120) NOT NULL UNIQUE,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  old_price DECIMAL(12,2) NULL,
  discount DECIMAL(5,2) NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  rating DECIMAL(3,2) NOT NULL DEFAULT 4.50,
  review_count INT NOT NULL DEFAULT 0,
  warranty VARCHAR(255) NULL,
  short_description TEXT NULL,
  description TEXT NULL,
  specifications JSON NULL,
  images JSON NOT NULL,
  tags JSON NULL,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  best_seller TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_products_brand (brand_id),
  INDEX idx_products_category (category_id),
  INDEX idx_products_active (active),
  INDEX idx_products_price (price),
  INDEX idx_products_featured (featured),
  INDEX idx_products_best_seller (best_seller)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  shipping_full_name VARCHAR(150) NULL,
  shipping_phone VARCHAR(50) NULL,
  shipping_address TEXT NULL,
  shipping_city VARCHAR(120) NULL,
  shipping_province VARCHAR(120) NULL,
  shipping_postal_code VARCHAR(30) NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_method ENUM('cod') NOT NULL DEFAULT 'cod',
  status ENUM('pending','confirmed','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_orders_user (user_id),
  INDEX idx_orders_status (status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(500) NULL,
  price DECIMAL(12,2) NOT NULL,
  quantity INT NOT NULL,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_order_items_order (order_id),
  INDEX idx_order_items_product (product_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  rating DECIMAL(2,1) NOT NULL,
  comment VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_review_product_user (product_id, user_id),
  CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS store_settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(50) NOT NULL UNIQUE DEFAULT 'main',
  store_name VARCHAR(150) NOT NULL DEFAULT 'KPK Electronics',
  announcement VARCHAR(500) NOT NULL DEFAULT 'PREMIUM APPLIANCES · TRUSTED BRANDS · DELIVERY ACROSS PAKISTAN',
  hero_eyebrow VARCHAR(255) NOT NULL DEFAULT 'THE NEW STANDARD FOR HOME APPLIANCES',
  hero_title VARCHAR(255) NOT NULL DEFAULT 'Upgrade your home. Live smarter.',
  hero_subtitle TEXT NOT NULL,
  hero_primary_label VARCHAR(100) NOT NULL DEFAULT 'Explore appliances',
  hero_primary_url VARCHAR(255) NOT NULL DEFAULT '/shop',
  hero_secondary_label VARCHAR(100) NOT NULL DEFAULT 'Today''s best deals',
  hero_secondary_url VARCHAR(255) NOT NULL DEFAULT '/shop?featured=true',
  hero_accent VARCHAR(100) NOT NULL DEFAULT 'SMARTER LIVING',
  free_shipping_threshold DECIMAL(12,2) NOT NULL DEFAULT 50000,
  cod_enabled TINYINT(1) NOT NULL DEFAULT 1,
  support_phone VARCHAR(50) NULL,
  support_email VARCHAR(255) NULL,
  primary_accent VARCHAR(30) NOT NULL DEFAULT '#b7ff3c',
  dark_background VARCHAR(30) NOT NULL DEFAULT '#06080b',
  light_text VARCHAR(30) NOT NULL DEFAULT '#f5f7f2',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Migrated catalog and settings data
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (1,'Dawlance','dawlance','Pakistan','Dawlance appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.740Z','2026-08-12T20:49:42.740Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (2,'Haier','haier','Pakistan','Haier appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.743Z','2026-08-12T20:49:42.743Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (3,'PEL','pel','Pakistan','PEL appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.743Z','2026-08-12T20:49:42.743Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (4,'Orient','orient','Pakistan','Orient appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.743Z','2026-08-12T20:49:42.743Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (5,'Gree','gree','China','Gree appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.743Z','2026-08-12T20:49:42.743Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (6,'Kenwood','kenwood','United Kingdom','Kenwood appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.743Z','2026-08-12T20:49:42.743Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (7,'Homage','homage','Pakistan','Homage appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (8,'Waves','waves','Pakistan','Waves appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (9,'Super Asia','super-asia','Pakistan','Super Asia appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (10,'TCL','tcl','China','TCL appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (11,'Samsung','samsung','South Korea','Samsung appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (12,'LG','lg','South Korea','LG appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (13,'Midea','midea','China','Midea appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (14,'EcoStar','ecostar','Pakistan','EcoStar appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (15,'Changhong Ruba','changhong-ruba','China','Changhong Ruba appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (16,'Westpoint','westpoint','Pakistan','Westpoint appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (17,'NasGas','nasgas','Pakistan','NasGas appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (18,'Philips','philips','Netherlands','Philips appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.744Z','2026-08-12T20:49:42.744Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (19,'Signature','signature','Pakistan','Signature appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.745Z','2026-08-12T20:49:42.745Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (20,'Boss','boss','Pakistan','Boss appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.745Z','2026-08-12T20:49:42.745Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (21,'Varioline','varioline','Pakistan','Varioline appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.745Z','2026-08-12T20:49:42.745Z');
INSERT INTO brands (id,name,slug,country,description,logo,active,created_at,updated_at) VALUES (22,'National','national','Japan','National appliances and electronics available in Pakistan.',NULL,1,'2026-08-12T20:49:42.745Z','2026-08-12T20:49:42.745Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (1,'Air Conditioners','air-conditioners','Cooling','Air Conditioners for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (2,'Refrigerators','refrigerators','Kitchen','Refrigerators for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (3,'Deep Freezers','deep-freezers','Kitchen','Deep Freezers for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (4,'Washing Machines','washing-machines','Laundry','Washing Machines for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (5,'LED TVs','led-tvs','Entertainment','LED TVs for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (6,'Microwave Ovens','microwave-ovens','Kitchen','Microwave Ovens for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (7,'Water Dispensers','water-dispensers','Kitchen','Water Dispensers for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (8,'Water Heaters','water-heaters','Home','Water Heaters for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (9,'Room Heaters','room-heaters','Home','Room Heaters for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (10,'Kitchen Appliances','kitchen-appliances','Kitchen','Kitchen Appliances for modern Pakistani homes.',1,'2026-08-12T20:49:42.761Z','2026-08-12T20:49:42.761Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (11,'Vacuum Cleaners','vacuum-cleaners','Cleaning','Vacuum Cleaners for modern Pakistani homes.',1,'2026-08-12T20:49:42.762Z','2026-08-12T20:49:42.762Z');
INSERT INTO categories (id,name,slug,icon,description,active,created_at,updated_at) VALUES (12,'Fans','fans','Cooling','Fans for modern Pakistani homes.',1,'2026-08-12T20:49:42.762Z','2026-08-12T20:49:42.762Z');
INSERT INTO users (id,name,email,password,role,phone,addresses,created_at,updated_at) VALUES (1,'Store Administrator','admin@kpkelectronics.pk','$2a$12$izdQOEAbKSoBIfRCZTwtwuq8bJtReSYs7.a8ZNpX3UFoWZhHVyrQq','admin',NULL,'[]','2026-08-12T18:16:06.207Z','2026-08-12T21:49:21.956Z');
INSERT INTO users (id,name,email,password,role,phone,addresses,created_at,updated_at) VALUES (2,'Store Administrator','admin@kpkelectronics.com','$2a$12$bhogA36ksHWKz3jt6XQ7Jud2Yz9fecopOXQPT.ZKwwLPE18qYRy2u','admin',NULL,'[]','2026-08-14T14:28:43.499Z','2026-08-15T12:54:46.163Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (1,'Dawlance Inverter 1.5 Ton AC','dawlance-inverter-1-5-ton-ac-1',1,1,'KPK-0001',119999,129599,7,12,4.4,10,'10 years compressor','A practical air conditioners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"1.5 Ton","Technology":"Inverter","Refrigerant":"R-32","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/ac.svg"]','["Dawlance","Air Conditioners","ac","Pakistan"]',1,1,1,'2026-08-12T20:49:42.821Z','2026-08-12T20:49:42.821Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (2,'Haier Inverter 1.5 Ton AC','haier-inverter-1-5-ton-ac-2',2,1,'KPK-0002',124999,134999,7,10,4.5,11,'10 years compressor','A practical air conditioners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"1.5 Ton","Technology":"Inverter","Refrigerant":"R-32","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/ac.svg"]','["Haier","Air Conditioners","ac","Pakistan"]',0,0,1,'2026-08-12T20:49:42.823Z','2026-08-12T20:49:42.823Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (3,'Gree Inverter 1.5 Ton AC','gree-inverter-1-5-ton-ac-3',5,1,'KPK-0003',139999,151199,7,8,4.6000000000000005,12,'10 years compressor','A practical air conditioners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"1.5 Ton","Technology":"Inverter","Refrigerant":"R-32","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/ac.svg"]','["Gree","Air Conditioners","ac","Pakistan"]',0,0,1,'2026-08-12T20:49:42.823Z','2026-08-12T20:49:42.823Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (4,'Orient Inverter 1.5 Ton AC','orient-inverter-1-5-ton-ac-4',4,1,'KPK-0004',104999,113399,7,14,4.7,13,'10 years compressor','A practical air conditioners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"1.5 Ton","Technology":"Inverter","Refrigerant":"R-32","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/ac.svg"]','["Orient","Air Conditioners","ac","Pakistan"]',0,0,1,'2026-08-12T20:49:42.823Z','2026-08-12T20:49:42.823Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (5,'Kenwood Inverter 1.5 Ton AC','kenwood-inverter-1-5-ton-ac-5',6,1,'KPK-0005',109999,118799,7,9,4.800000000000001,14,'10 years compressor','A practical air conditioners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"1.5 Ton","Technology":"Inverter","Refrigerant":"R-32","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/ac.svg"]','["Kenwood","Air Conditioners","ac","Pakistan"]',0,1,1,'2026-08-12T20:49:42.823Z','2026-08-12T20:49:42.823Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (6,'Dawlance Double Door Inverter Refrigerator','dawlance-double-door-inverter-refrigerator-6',1,2,'KPK-0006',134999,145799,7,9,4.9,15,'10 years compressor','A practical refrigerators choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"450 L","Cooling":"Inverter","Type":"Double Door","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/fridge.svg"]','["Dawlance","Refrigerators","fridge","Pakistan"]',1,0,1,'2026-08-12T20:49:42.823Z','2026-08-12T20:49:42.823Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (7,'Haier Double Door Inverter Refrigerator','haier-double-door-inverter-refrigerator-7',2,2,'KPK-0007',139999,151199,7,11,4.4,16,'10 years compressor','A practical refrigerators choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"450 L","Cooling":"Inverter","Type":"Double Door","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/fridge.svg"]','["Haier","Refrigerators","fridge","Pakistan"]',1,0,1,'2026-08-12T20:49:42.823Z','2026-08-12T20:49:42.823Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (8,'PEL Double Door Refrigerator','pel-double-door-refrigerator-8',3,2,'KPK-0008',119999,129599,7,13,4.5,17,'10 years compressor','A practical refrigerators choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"450 L","Cooling":"Inverter","Type":"Double Door","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/fridge.svg"]','["PEL","Refrigerators","fridge","Pakistan"]',0,0,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (9,'Orient Inverter Refrigerator','orient-inverter-refrigerator-9',4,2,'KPK-0009',109999,118799,7,7,4.6000000000000005,18,'10 years compressor','A practical refrigerators choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"450 L","Cooling":"Inverter","Type":"Double Door","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/fridge.svg"]','["Orient","Refrigerators","fridge","Pakistan"]',0,1,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (10,'Waves Frost Free Refrigerator','waves-frost-free-refrigerator-10',8,2,'KPK-0010',99999,107999,7,10,4.7,19,'10 years compressor','A practical refrigerators choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"450 L","Cooling":"Inverter","Type":"Double Door","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/fridge.svg"]','["Waves","Refrigerators","fridge","Pakistan"]',0,0,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (11,'Haier Chest Deep Freezer','haier-chest-deep-freezer-11',2,3,'KPK-0011',89999,97199,7,12,4.800000000000001,20,'10 years compressor','A practical deep freezers choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"300 L","Type":"Deep Freezer","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/freezer.svg"]','["Haier","Deep Freezers","freezer","Pakistan"]',0,0,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (12,'Dawlance Chest Deep Freezer','dawlance-chest-deep-freezer-12',1,3,'KPK-0012',84999,91799,7,15,4.9,21,'10 years compressor','A practical deep freezers choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"300 L","Type":"Deep Freezer","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/freezer.svg"]','["Dawlance","Deep Freezers","freezer","Pakistan"]',0,0,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (13,'Waves Deep Freezer','waves-deep-freezer-13',8,3,'KPK-0013',79999,86399,7,10,4.4,22,'10 years compressor','A practical deep freezers choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"300 L","Type":"Deep Freezer","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/freezer.svg"]','["Waves","Deep Freezers","freezer","Pakistan"]',1,1,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (14,'PEL Deep Freezer','pel-deep-freezer-14',3,3,'KPK-0014',82999,89639,7,9,4.5,23,'10 years compressor','A practical deep freezers choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"300 L","Type":"Deep Freezer","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/freezer.svg"]','["PEL","Deep Freezers","freezer","Pakistan"]',0,0,1,'2026-08-12T20:49:42.824Z','2026-08-12T20:49:42.824Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (15,'Dawlance Fully Automatic Washing Machine','dawlance-fully-automatic-washing-machine-15',1,4,'KPK-0015',99999,107999,7,9,4.6000000000000005,24,'10 years motor','A practical washing machines choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"10 kg","Type":"Fully Automatic","Motor":"Inverter","Voltage":"220V","Warranty":"10 years motor"}','["/uploads/seed/washer.svg"]','["Dawlance","Washing Machines","washer","Pakistan"]',1,0,1,'2026-08-12T20:49:42.825Z','2026-08-12T20:49:42.825Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (16,'Haier Fully Automatic Inverter Washer','haier-fully-automatic-inverter-washer-16',2,4,'KPK-0016',109999,118799,7,10,4.7,25,'10 years motor','A practical washing machines choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"10 kg","Type":"Fully Automatic","Motor":"Inverter","Voltage":"220V","Warranty":"10 years motor"}','["/uploads/seed/washer.svg"]','["Haier","Washing Machines","washer","Pakistan"]',1,0,1,'2026-08-12T20:49:42.825Z','2026-08-12T20:49:42.825Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (17,'Kenwood Automatic Washing Machine','kenwood-automatic-washing-machine-17',6,4,'KPK-0017',92999,100439,7,8,4.800000000000001,26,'10 years motor','A practical washing machines choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"10 kg","Type":"Fully Automatic","Motor":"Inverter","Voltage":"220V","Warranty":"10 years motor"}','["/uploads/seed/washer.svg"]','["Kenwood","Washing Machines","washer","Pakistan"]',0,1,1,'2026-08-12T20:49:42.825Z','2026-08-12T20:49:42.825Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (18,'Super Asia Automatic Washing Machine','super-asia-automatic-washing-machine-18',9,4,'KPK-0018',74999,80999,7,13,4.9,27,'10 years motor','A practical washing machines choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"10 kg","Type":"Fully Automatic","Motor":"Inverter","Voltage":"220V","Warranty":"10 years motor"}','["/uploads/seed/washer.svg"]','["Super Asia","Washing Machines","washer","Pakistan"]',0,0,1,'2026-08-12T20:49:42.825Z','2026-08-12T20:49:42.825Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (19,'Homage Fully Automatic Washer','homage-fully-automatic-washer-19',7,4,'KPK-0019',81999,88559,7,11,4.4,28,'10 years motor','A practical washing machines choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"10 kg","Type":"Fully Automatic","Motor":"Inverter","Voltage":"220V","Warranty":"10 years motor"}','["/uploads/seed/washer.svg"]','["Homage","Washing Machines","washer","Pakistan"]',0,0,1,'2026-08-12T20:49:42.825Z','2026-08-12T20:49:42.825Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (20,'TCL 55 Inch 4K Smart TV','tcl-55-inch-4k-smart-tv-20',10,5,'KPK-0020',119999,129599,7,10,4.5,29,'2 years','A practical led tvs choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Screen":"55 inch","Resolution":"4K UHD","Smart":"Google TV / Smart OS","Connectivity":"Wi-Fi, HDMI, USB","Warranty":"2 years"}','["/uploads/seed/tv.svg"]','["TCL","LED TVs","tv","Pakistan"]',1,0,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (21,'Samsung 55 Inch 4K Smart TV','samsung-55-inch-4k-smart-tv-21',11,5,'KPK-0021',164999,178199,7,7,4.6000000000000005,30,'2 years','A practical led tvs choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Screen":"55 inch","Resolution":"4K UHD","Smart":"Google TV / Smart OS","Connectivity":"Wi-Fi, HDMI, USB","Warranty":"2 years"}','["/uploads/seed/tv.svg"]','["Samsung","LED TVs","tv","Pakistan"]',1,1,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (22,'Haier 55 Inch 4K Smart TV','haier-55-inch-4k-smart-tv-22',2,5,'KPK-0022',109999,118799,7,8,4.7,31,'2 years','A practical led tvs choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Screen":"55 inch","Resolution":"4K UHD","Smart":"Google TV / Smart OS","Connectivity":"Wi-Fi, HDMI, USB","Warranty":"2 years"}','["/uploads/seed/tv.svg"]','["Haier","LED TVs","tv","Pakistan"]',0,0,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (23,'EcoStar 55 Inch 4K Smart TV','ecostar-55-inch-4k-smart-tv-23',14,5,'KPK-0023',89999,97199,7,12,4.800000000000001,32,'2 years','A practical led tvs choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Screen":"55 inch","Resolution":"4K UHD","Smart":"Google TV / Smart OS","Connectivity":"Wi-Fi, HDMI, USB","Warranty":"2 years"}','["/uploads/seed/tv.svg"]','["EcoStar","LED TVs","tv","Pakistan"]',0,0,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (24,'Changhong Ruba 55 Inch 4K Smart TV','changhong-ruba-55-inch-4k-smart-tv-24',15,5,'KPK-0024',94999,102599,7,9,4.9,33,'2 years','A practical led tvs choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Screen":"55 inch","Resolution":"4K UHD","Smart":"Google TV / Smart OS","Connectivity":"Wi-Fi, HDMI, USB","Warranty":"2 years"}','["/uploads/seed/tv.svg"]','["Changhong Ruba","LED TVs","tv","Pakistan"]',0,0,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (25,'Dawlance 30L Digital Microwave','dawlance-30l-digital-microwave-25',1,6,'KPK-0025',26999,29159,7,18,4.4,34,'1 year','A practical microwave ovens choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"30 L","Type":"Digital","Power":"900 W","Modes":"Grill + Microwave","Warranty":"1 year"}','["/uploads/seed/microwave.svg"]','["Dawlance","Microwave Ovens","microwave","Pakistan"]',0,1,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (26,'Haier 30L Microwave Oven','haier-30l-microwave-oven-26',2,6,'KPK-0026',28999,31319,7,15,4.5,35,'1 year','A practical microwave ovens choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"30 L","Type":"Digital","Power":"900 W","Modes":"Grill + Microwave","Warranty":"1 year"}','["/uploads/seed/microwave.svg"]','["Haier","Microwave Ovens","microwave","Pakistan"]',0,0,1,'2026-08-12T20:49:42.826Z','2026-08-12T20:49:42.826Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (27,'PEL Digital Microwave Oven','pel-digital-microwave-oven-27',3,6,'KPK-0027',23999,25919,7,16,4.6000000000000005,36,'1 year','A practical microwave ovens choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"30 L","Type":"Digital","Power":"900 W","Modes":"Grill + Microwave","Warranty":"1 year"}','["/uploads/seed/microwave.svg"]','["PEL","Microwave Ovens","microwave","Pakistan"]',0,0,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (28,'Kenwood Blender & Grinder Set','kenwood-blender-grinder-set-28',6,10,'KPK-0028',18999,20519,7,20,4.7,37,'1 year','A practical kitchen appliances choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Multi-purpose","Voltage":"220V","Finish":"Stainless steel","Warranty":"1 year"}','["/uploads/seed/kitchen.svg"]','["Kenwood","Kitchen Appliances","kitchen","Pakistan"]',0,0,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (29,'Westpoint Kitchen Blender Set','westpoint-kitchen-blender-set-29',16,10,'KPK-0029',12999,14039,7,22,4.800000000000001,38,'1 year','A practical kitchen appliances choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Multi-purpose","Voltage":"220V","Finish":"Stainless steel","Warranty":"1 year"}','["/uploads/seed/kitchen.svg"]','["Westpoint","Kitchen Appliances","kitchen","Pakistan"]',0,1,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (30,'Haier Hot & Cold Water Dispenser','haier-hot-cold-water-dispenser-30',2,7,'KPK-0030',29999,32399,7,17,4.9,39,'1 year','A practical water dispensers choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Hot & Cold","Cooling":"Compressor","Cabinet":"ABS","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/dispenser.svg"]','["Haier","Water Dispensers","dispenser","Pakistan"]',0,0,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (31,'Dawlance Hot & Cold Dispenser','dawlance-hot-cold-dispenser-31',1,7,'KPK-0031',27999,30239,7,15,4.4,40,'1 year','A practical water dispensers choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Hot & Cold","Cooling":"Compressor","Cabinet":"ABS","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/dispenser.svg"]','["Dawlance","Water Dispensers","dispenser","Pakistan"]',0,0,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (32,'Super Asia Electric Water Heater','super-asia-electric-water-heater-32',9,8,'KPK-0032',34999,37799,7,10,4.5,41,'1 year','A practical water heaters choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Electric/Gas family","Safety":"Auto cut-off","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/heater.svg"]','["Super Asia","Water Heaters","heater","Pakistan"]',0,0,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (33,'Haier Electric Water Heater','haier-electric-water-heater-33',2,8,'KPK-0033',41999,45359,7,8,4.6000000000000005,42,'1 year','A practical water heaters choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Electric/Gas family","Safety":"Auto cut-off","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/heater.svg"]','["Haier","Water Heaters","heater","Pakistan"]',0,1,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (34,'Homage Room Heater','homage-room-heater-34',7,9,'KPK-0034',8999,9719,7,25,4.7,43,'1 year','A practical room heaters choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Electric/Gas family","Safety":"Auto cut-off","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/heater.svg"]','["Homage","Room Heaters","heater","Pakistan"]',0,0,1,'2026-08-12T20:49:42.827Z','2026-08-12T20:49:42.827Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (35,'LG Bagless Vacuum Cleaner','lg-bagless-vacuum-cleaner-35',12,11,'KPK-0035',32999,35639,7,8,4.800000000000001,44,'1 year','A practical vacuum cleaners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Bagless","Power":"1600 W","Filtration":"HEPA","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/vacuum.svg"]','["LG","Vacuum Cleaners","vacuum","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (36,'Samsung Bagless Vacuum Cleaner','samsung-bagless-vacuum-cleaner-36',11,11,'KPK-0036',44999,48599,7,7,4.9,45,'1 year','A practical vacuum cleaners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Bagless","Power":"1600 W","Filtration":"HEPA","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/vacuum.svg"]','["Samsung","Vacuum Cleaners","vacuum","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (37,'Philips Bagless Vacuum Cleaner','philips-bagless-vacuum-cleaner-37',18,11,'KPK-0037',24999,26999,7,9,4.4,46,'1 year','A practical vacuum cleaners choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Bagless","Power":"1600 W","Filtration":"HEPA","Voltage":"220V","Warranty":"1 year"}','["/uploads/seed/vacuum.svg"]','["Philips","Vacuum Cleaners","vacuum","Pakistan"]',0,1,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (38,'NasGas Kitchen Hob','nasgas-kitchen-hob-38',17,10,'KPK-0038',24999,26999,7,14,4.5,47,'1 year','A practical kitchen appliances choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Multi-purpose","Voltage":"220V","Finish":"Stainless steel","Warranty":"1 year"}','["/uploads/seed/kitchen.svg"]','["NasGas","Kitchen Appliances","kitchen","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (39,'Boss Kitchen Blender Set','boss-kitchen-blender-set-39',20,10,'KPK-0039',10999,11879,7,18,4.6000000000000005,48,'1 year','A practical kitchen appliances choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Multi-purpose","Voltage":"220V","Finish":"Stainless steel","Warranty":"1 year"}','["/uploads/seed/kitchen.svg"]','["Boss","Kitchen Appliances","kitchen","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (40,'Signature Electric Oven','signature-electric-oven-40',19,10,'KPK-0040',22999,24839,7,12,4.7,49,'1 year','A practical kitchen appliances choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Multi-purpose","Voltage":"220V","Finish":"Stainless steel","Warranty":"1 year"}','["/uploads/seed/kitchen.svg"]','["Signature","Kitchen Appliances","kitchen","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (41,'Varioline Double Door Refrigerator','varioline-double-door-refrigerator-41',21,2,'KPK-0041',104999,113399,7,7,4.800000000000001,50,'10 years compressor','A practical refrigerators choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Capacity":"450 L","Cooling":"Inverter","Type":"Double Door","Voltage":"220V","Warranty":"10 years compressor"}','["/uploads/seed/fridge.svg"]','["Varioline","Refrigerators","fridge","Pakistan"]',0,1,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (42,'National Energy Saver Ceiling Fan','national-energy-saver-ceiling-fan-42',22,12,'KPK-0042',13999,15119,7,14,4.9,51,'2 years','A practical fans choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Ceiling / Pedestal","Motor":"Energy efficient","Voltage":"220V","Warranty":"2 years"}','["/uploads/seed/fan.svg"]','["National","Fans","fan","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (43,'Super Asia Energy Saver Ceiling Fan','super-asia-energy-saver-ceiling-fan-43',9,12,'KPK-0043',11999,12959,7,20,4.4,52,'2 years','A practical fans choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Ceiling / Pedestal","Motor":"Energy efficient","Voltage":"220V","Warranty":"2 years"}','["/uploads/seed/fan.svg"]','["Super Asia","Fans","fan","Pakistan"]',0,0,1,'2026-08-12T20:49:42.828Z','2026-08-12T20:49:42.828Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (44,'PEL Energy Saver Ceiling Fan','pel-energy-saver-ceiling-fan-44',3,12,'KPK-0044',10999,11879,7,18,4.5,53,'2 years','A practical fans choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Ceiling / Pedestal","Motor":"Energy efficient","Voltage":"220V","Warranty":"2 years"}','["/uploads/seed/fan.svg"]','["PEL","Fans","fan","Pakistan"]',0,0,0,'2026-08-12T20:49:42.829Z','2026-08-14T20:13:50.530Z');
INSERT INTO products (id,name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active,created_at,updated_at) VALUES (45,'Orient Energy Saver Ceiling Fan','orient-energy-saver-ceiling-fan-45',4,12,'KPK-0045',12999,14039,7,16,4.6000000000000005,54,'2 years','A practical fans choice for Pakistani homes.','Demo catalog listing for KPK Electronics. Verify exact model specifications and warranty terms with the product page before purchase.','{"Type":"Ceiling / Pedestal","Motor":"Energy efficient","Voltage":"220V","Warranty":"2 years"}','["/uploads/seed/fan.svg"]','["Orient","Fans","fan","Pakistan"]',0,1,1,'2026-08-12T20:49:42.829Z','2026-08-12T20:49:42.829Z');
INSERT INTO store_settings (id,setting_key,store_name,announcement,hero_eyebrow,hero_title,hero_subtitle,hero_primary_label,hero_primary_url,hero_secondary_label,hero_secondary_url,hero_accent,free_shipping_threshold,cod_enabled,support_phone,support_email,primary_accent,dark_background,light_text,created_at,updated_at) VALUES (1,'main','KPK Electronics','PREMIUM APPLIANCES · TRUSTED BRANDS · DELIVERY ACROSS PAKISTAN','THE NEW STANDARD FOR HOME APPLIANCES','Smart appliances for a smarter home','Discover premium appliances from trusted brands, with transparent pricing and a shopping experience designed around your home.','Explore appliances','/shop','Today''s best deals','/shop?featured=true','SMARTER LIVING',50000,1,'','','#b7ff3c','#06080b','#f5f7f2','2026-08-14T14:28:43.510Z','2026-08-15T12:57:14.896Z');
