import express from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import { query, transaction } from '../db.js';
import { productView, brandView, categoryView, jsonParse } from '../utils/dbHelpers.js';
import { protect, adminOnly } from '../middleware/auth.js';
const router=express.Router();
const uploadDir=path.resolve('uploads/products');fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(_,file,cb)=>cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(file.originalname).toLowerCase()}`)});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(_,file,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype))});

const baseSelect=`SELECT p.*, b.id AS b_id,b.name AS b_name,b.slug AS b_slug,b.country AS b_country,b.description AS b_description,b.logo AS b_logo,b.active AS b_active,b.created_at AS b_created_at,b.updated_at AS b_updated_at,c.id AS c_id,c.name AS c_name,c.slug AS c_slug,c.icon AS c_icon,c.description AS c_description,c.active AS c_active,c.created_at AS c_created_at,c.updated_at AS c_updated_at FROM products p JOIN brands b ON b.id=p.brand_id JOIN categories c ON c.id=p.category_id`;
function mapProduct(r){const brand=r.b_id?{id:r.b_id,name:r.b_name,slug:r.b_slug,country:r.b_country,description:r.b_description,logo:r.b_logo,active:r.b_active,created_at:r.b_created_at,updated_at:r.b_updated_at}:null;const category=r.c_id?{id:r.c_id,name:r.c_name,slug:r.c_slug,icon:r.c_icon,description:r.c_description,active:r.c_active,created_at:r.c_created_at,updated_at:r.c_updated_at}:null;return productView(r,brand,category);}
function numeric(v,d=0){return v===''||v===undefined||v===null?d:Number(v)}
function parseBody(body){let specifications=body.specifications;try{if(typeof specifications==='string')specifications=JSON.parse(specifications||'{}')}catch{specifications={}};let tags=body.tags;if(typeof tags==='string')tags=tags.split(',').map(s=>s.trim()).filter(Boolean);return {...body,specifications:specifications||{},tags:Array.isArray(tags)?tags:[],price:numeric(body.price),oldPrice:body.oldPrice===''?null:numeric(body.oldPrice,null),discount:numeric(body.discount),stock:numeric(body.stock),rating:numeric(body.rating,4.5),reviewCount:numeric(body.reviewCount),featured:body.featured==='true'||body.featured===true,bestSeller:body.bestSeller==='true'||body.bestSeller===true,active:body.active===undefined?true:(body.active==='true'||body.active===true)}}

router.get('/',async(req,res)=>{try{const {search,category,brand,min,max,sort='newest',featured,bestSeller}=req.query;let where=['p.active=1'],params=[];if(search){where.push('(p.name LIKE ? OR p.sku LIKE ? OR CAST(p.tags AS CHAR) LIKE ?)');const s=`%${search}%`;params.push(s,s,s)}if(category){let id=null;if(/^\d+$/.test(category))id=category;else{id=(await query('SELECT id FROM categories WHERE slug=? LIMIT 1',[category]))[0]?.id}if(!id)return res.json([]);where.push('p.category_id=?');params.push(id)}if(brand){let id=null;if(/^\d+$/.test(brand))id=brand;else{id=(await query('SELECT id FROM brands WHERE slug=? LIMIT 1',[brand]))[0]?.id}if(!id)return res.json([]);where.push('p.brand_id=?');params.push(id)}if(min){where.push('p.price>=?');params.push(Number(min))}if(max){where.push('p.price<=?');params.push(Number(max))}if(featured==='true')where.push('p.featured=1');if(bestSeller==='true')where.push('p.best_seller=1');const sortMap={newest:'p.created_at DESC',priceAsc:'p.price ASC',priceDesc:'p.price DESC',rating:'p.rating DESC'};const rows=await query(`${baseSelect} WHERE ${where.join(' AND ')} ORDER BY ${sortMap[sort]||sortMap.newest} LIMIT 100`,params);res.json(rows.map(mapProduct));}catch(e){res.status(500).json({message:'Could not load products',error:e.message})}});

router.get('/admin/all',protect,adminOnly,async(req,res)=>{try{const rows=await query(`${baseSelect} ORDER BY p.created_at DESC`);res.json(rows.map(mapProduct))}catch(e){res.status(500).json({message:'Could not load admin products',error:e.message})}});

router.get('/:slug',async(req,res)=>{try{const rows=await query(`${baseSelect} WHERE p.slug=? AND p.active=1 LIMIT 1`,[req.params.slug]);const r=rows[0];if(!r)return res.status(404).json({message:'Product not found'});const product=mapProduct(r);const reviews=await query(`SELECT rv.*,u.name AS user_name FROM reviews rv JOIN users u ON u.id=rv.user_id WHERE rv.product_id=? ORDER BY rv.created_at DESC`,[r.id]);res.json({product,reviews:reviews.map(x=>({_id:x.id,id:x.id,product:x.product_id,user:{_id:x.user_id,id:x.user_id,name:x.user_name},rating:Number(x.rating),comment:x.comment,createdAt:x.created_at,updatedAt:x.updated_at}))});}catch(e){res.status(500).json({message:'Could not load product',error:e.message})}});

router.post('/',protect,adminOnly,upload.array('images',6),async(req,res)=>{try{const body=parseBody(req.body);const images=(req.files||[]).map(f=>`/uploads/products/${f.filename}`);if(!images.length)return res.status(400).json({message:'At least one real product image is required.'});if(body.oldPrice&&body.price&&!body.discount)body.discount=Math.max(0,Math.round(((body.oldPrice-body.price)/body.oldPrice)*100));const r=await query(`INSERT INTO products (name,slug,brand_id,category_id,sku,price,old_price,discount,stock,rating,review_count,warranty,short_description,description,specifications,images,tags,featured,best_seller,active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[body.name,body.slug,body.brand,body.category,body.sku,body.price,body.oldPrice,body.discount,body.stock,body.rating,body.reviewCount,body.warranty||null,body.shortDescription||null,body.description||null,JSON.stringify(body.specifications),JSON.stringify(images),JSON.stringify(body.tags),body.featured?1:0,body.bestSeller?1:0,body.active?1:0]);const row=(await query(`${baseSelect} WHERE p.id=?`,[r.insertId]))[0];res.status(201).json(mapProduct(row));}catch(e){res.status(400).json({message:'Product creation failed',error:e.message})}});

router.put('/:id',protect,adminOnly,upload.array('images',6),async(req,res)=>{try{const current=(await query('SELECT * FROM products WHERE id=?',[req.params.id]))[0];if(!current)return res.status(404).json({message:'Product not found'});const body=parseBody(req.body);if(req.files?.length)body.images=req.files.map(f=>`/uploads/products/${f.filename}`);else body.images=jsonParse(current.images,[]);if(!body.images.length)return res.status(400).json({message:'A product must keep at least one real image.'});if(body.oldPrice&&body.price&&!body.discount)body.discount=Math.max(0,Math.round(((body.oldPrice-body.price)/body.oldPrice)*100));await query(`UPDATE products SET name=?,slug=?,brand_id=?,category_id=?,sku=?,price=?,old_price=?,discount=?,stock=?,rating=?,review_count=?,warranty=?,short_description=?,description=?,specifications=?,images=?,tags=?,featured=?,best_seller=?,active=? WHERE id=?`,[body.name,body.slug,body.brand,body.category,body.sku,body.price,body.oldPrice,body.discount,body.stock,body.rating,body.reviewCount,body.warranty||null,body.shortDescription||null,body.description||null,JSON.stringify(body.specifications),JSON.stringify(body.images),JSON.stringify(body.tags),body.featured?1:0,body.bestSeller?1:0,body.active?1:0,req.params.id]);const row=(await query(`${baseSelect} WHERE p.id=?`,[req.params.id]))[0];res.json(mapProduct(row));}catch(e){res.status(400).json({message:'Product update failed',error:e.message})}});

router.delete('/:id',protect,adminOnly,async(req,res)=>{await query('UPDATE products SET active=0 WHERE id=?',[req.params.id]);res.json({message:'Product archived'})});

router.post('/:id/reviews',protect,async(req,res)=>{try{const rating=Number(req.body.rating);const comment=String(req.body.comment||'').trim();if(rating<1||rating>5||!comment)return res.status(400).json({message:'Valid rating and comment are required'});const r=await query('INSERT INTO reviews (product_id,user_id,rating,comment) VALUES (?,?,?,?)',[req.params.id,req.user._id,rating,comment]);const agg=(await query('SELECT AVG(rating) avg, COUNT(*) count FROM reviews WHERE product_id=?',[req.params.id]))[0];await query('UPDATE products SET rating=?,review_count=? WHERE id=?',[Number(agg.avg||0),Number(agg.count||0),req.params.id]);const row=(await query('SELECT rv.*,u.name AS user_name FROM reviews rv JOIN users u ON u.id=rv.user_id WHERE rv.id=?',[r.insertId]))[0];res.status(201).json({_id:row.id,id:row.id,product:row.product_id,user:{_id:row.user_id,id:row.user_id,name:row.user_name},rating:Number(row.rating),comment:row.comment,createdAt:row.created_at,updatedAt:row.updated_at});}catch(e){res.status(400).json({message:'Review could not be added',error:e.message})}});
export default router;
